<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Agency Performance Report</title>
    <style>
        body {
            font-family: DejaVu Sans, Arial, Helvetica, sans-serif;
            font-size: 12px;
            color: #222;
            margin: 30px;
        }
        h2, h4 {
            margin-bottom: 5px;
        }
        .report-meta {
            margin-bottom: 20px;
        }
        .report-meta td {
            padding-right: 40px;
            font-size: 12px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 16px;
        }
        th, td {
            border: 1px solid #aaa;
            padding: 8px 6px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) td {
            background-color: #fcfcfc;
        }
        .footer {
            margin-top: 40px;
            font-size: 11px;
            text-align: right;
            color: #888;
        }
    </style>
</head>
<body>
    <h2>Agency Performance Report</h2>
    <h4>Malaysia Communications and Multimedia Commission (MCMC)</h4>
    <table class="report-meta">
        <tr>
            <td><strong>Generated At:</strong> {{ \Carbon\Carbon::now()->format('d M Y, H:i') }}</td>
            @if(isset($startDate) && isset($endDate))
                <td><strong>Date Range:</strong> {{ $startDate }} to {{ $endDate }}</td>
            @elseif(isset($startDate))
                <td><strong>From:</strong> {{ $startDate }}</td>
            @elseif(isset($endDate))
                <td><strong>Until:</strong> {{ $endDate }}</td>
            @endif
        </tr>
        <tr>
            @if(isset($selectedAgency) && $selectedAgency)
                <td><strong>Agency:</strong> {{ $selectedAgency }}</td>
            @endif
            @if(isset($selectedCategory) && $selectedCategory)
                <td><strong>Submission Category:</strong> {{ $selectedCategory }}</td>
            @endif
        </tr>
    </table>

    <table>
        <thead>
            <tr>
                <th style="width:40%;">Agency</th>
                <th style="width:20%;">Assigned</th>
                <th style="width:20%;">Resolved</th>
                <th style="width:20%;">Pending</th>
            </tr>
        </thead>
        <tbody>
        @forelse($performanceData as $agency)
            <tr>
                <td>{{ $agency['agency_name'] }}</td>
                <td>{{ $agency['assigned'] }}</td>
                <td>{{ $agency['resolved'] }}</td>
                <td>{{ $agency['pending'] }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="4" style="text-align:center;">No data available for the selected filters.</td>
            </tr>
        @endforelse
        </tbody>
    </table>

    <div class="footer">
        &copy; {{ date('Y') }} Malaysia Communications and Multimedia Commission (MCMC). Generated by MCMC Reporting System.
    </div>
</body>
</html>